# Generated by Django 5.0.3 on 2024-04-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='image',
            new_name='images',
        ),
    ]
