# Generated by Django 5.0.3 on 2024-04-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_image_student_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='images',
            new_name='image',
        ),
    ]
