# Generated by Django 5.0.3 on 2024-05-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=35)),
                ('Designation', models.CharField(max_length=35)),
                ('subject', models.CharField(max_length=35)),
                ('education', models.CharField(max_length=35)),
                ('exp', models.CharField(max_length=35)),
                ('image', models.ImageField(upload_to='bciit/image')),
            ],
        ),
    ]
